### ISSUE TITLE
Example data format

### ISSUE THREAD

**Issue by xxihe** [SpielmannLab/STIGMA#1]
Hi,

I am interested in testing your pipeline on our own data. Would you be able to provide any example dataset for us to have a test run? So we can get an idea of what format should use for input features, and what the output format looks like.

Best,
Xi

**Comment by Saranya-Balachandran** [comment]
Dear Xi,
I have added sample input and output tsp files under STIGMA/sample_dataset. Let me know if you have further queries

**Comment by xxihe** [comment]
Thank you so much!

However, the example files you updated are only for the second step in section 2"Model optimization and gene prioritization". I am still wondering how input.tsv files is generated using scripts mentioned in section 1 "Input Feature preprocessing". For example, what kind of input file looks like for the script Bsplines.R? If I am aslo using monocle3 as you mentioned in the paper, what kind output files I should get from monocle3 to serve as input for Bsplines.R?

Also, as for RandomForest_optimization.py in first step in section 2, what kind of input I should use here?

Best,
Xi

**Comment by Saranya-Balachandran** [comment]
Dear Xi,
The pseudo time that you generated are binned, and added as a metadata to the Seurat object, from which you can calculate average expression of all genes for the pseudo time bin column of the meta data, which is provided as input to the splines.

**Comment by xxihe** [comment]
Hi Saranya,

Thank you for the explanation. 

I have a quick question about the pseudo time bins generated from Monocle3. Do you consider to separate pseudo time from different trajectories(partitions), or you are pulling cells with the same pseudo time from different partitions together?

Best,
Xi

**Comment by Saranya-Balachandran** [comment]
Dear Xi,
The pseudotime is calculated per partition, and for each of the partition average expression of all genes per pseudo time bin is calculated

**Comment by xxihe** [comment]
Hi Saranya,

So the input matrix for splines is averaged expression matrix across each pseudo time bin per partition, with format as gene names as rows and pseudo time bin per partition as column?

Best,
Xi

**Comment by Saranya-Balachandran** [comment]
Dear Xi.
Yes. Splines was fit for each partition separately. Sample input file to the splines script can be found under STIGMA/sample_dataset.
